/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistemas.admon;

import java.awt.BorderLayout;


/**
 *
 * @author jose_
 */
public final class RellenarMatriz extends javax.swing.JPanel {

    /**
     * Creates new form RellenarMatriz
     */
    
    int NumFilas,NumColumnas,filaActual = 0,columnaActual = 0,totalDatos=0;
    float DatoMatriz;
    String NombreColumnas;
    String NFilas;
    String TextoNumFilas,TextoNumColumnas,TextoDatoMatriz;
    int MAX=10;
    float matriz[][]=new float[MAX][MAX];
    int clic=1;
    
    
    public void desactivarJTextField(){
        jTFNumFilas.setEnabled(true);
        jTFNumColumnas.setEnabled(true);
        jTFDatoMatriz.setEnabled(false);
        jTFNombreFilas.setEnabled(false);
        jTFNombreColumnas.setEnabled(false);
        jTFNumDatosFaltantes.setEnabled(false);

    }
    
    
    
    public RellenarMatriz() {
        initComponents();
         
        //rsscalelabel.RSScaleLabel.setScaleLabel(jLPuntos,"src/imagen/PUNTOSMEDIPAC2.png");
        desactivarJTextField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLPuntos = new javax.swing.JLabel();
        jTFNumFilas = new javax.swing.JTextField();
        jTFNumColumnas = new javax.swing.JTextField();
        jTFNombreFilas = new javax.swing.JTextField();
        jTFNombreColumnas = new javax.swing.JTextField();
        jTFNumDatosFaltantes = new javax.swing.JTextField();
        jTFDatoMatriz = new javax.swing.JTextField();
        jBAceptar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBCalcular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/MEDIPACPEQUE.png"))); // NOI18N

        jLPuntos.setText("Logo");

        jTFNumFilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumFilasActionPerformed(evt);
            }
        });

        jTFNumDatosFaltantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumDatosFaltantesActionPerformed(evt);
            }
        });

        jBAceptar.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jBAceptar.setText("Aceptar");
        jBAceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.lightGray, java.awt.Color.lightGray));
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        jBCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));

        jBCalcular.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBCalcular.setText("Calcular");
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setText("Rellene cada recuadro");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("Número de filas:");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setText("Número de columnas:");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel5.setText("Nombre de la fila:");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setText("Nombre de la columna:");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel7.setText("Datos por ingresar");

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setText("Ingrese cada dato:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFNumFilas)
                            .addComponent(jTFNumColumnas)
                            .addComponent(jTFNombreFilas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNombreColumnas)
                            .addComponent(jTFDatoMatriz)
                            .addComponent(jTFNumDatosFaltantes)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jBCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(235, 235, 235))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFNumFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jTFNumColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFNombreFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTFNombreColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTFNumDatosFaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTFDatoMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void clic1(){
        jTFNumFilas.setEnabled(false);
        jTFNumColumnas.setEnabled(false);
        jTFDatoMatriz.setEnabled(false);
        jTFNombreFilas.setEnabled(true);
        jTFNombreColumnas.setEnabled(true);
        
        clic=2;
    }
    
    public void clic2(){
        jTFNombreFilas.setEnabled(true);
        jTFNombreColumnas.setEnabled(true);
        jTFNumFilas.setEnabled(false);
        jTFNumColumnas.setEnabled(false);
        jTFDatoMatriz.setEnabled(false);
        jTFNumDatosFaltantes.setEnabled(false);
        
        TextoNumFilas = jTFNumFilas.getText();
        NumFilas = Integer.parseInt(TextoNumFilas);

        TextoNumColumnas = jTFNumColumnas.getText();
        NumColumnas = Integer.parseInt(TextoNumColumnas);
        
        //NFilas=jTFNombreFilas.getText();
        //NombreColumnas = jTFNombreColumnas.getText();
        
        jTFDatoMatriz.setEnabled(true);
        jTFNombreFilas.setEnabled(false);
        jTFNombreColumnas.setEnabled(false);
        
        totalDatos=NumFilas*NumColumnas;
        jTFNumDatosFaltantes.setText(Integer.toString(totalDatos));
        clic = 3;
    }
    
    public void clic3(){
        jTFNumFilas.setEnabled(false);
        jTFNumColumnas.setEnabled(false);
        jTFNombreFilas.setEnabled(false);
        jTFNombreColumnas.setEnabled(false);
        jTFDatoMatriz.setEnabled(true);
        jTFNumDatosFaltantes.setEnabled(false);

        //matriz = new int[NumFilas][NumColumnas];

        filaActual=0;
        columnaActual=0;
        

        clic = 4;
    }
    
    public void pasarmatriz(float [][] matriz){
       
        MatrizOriginal matriz_original=new MatrizOriginal(NombreColumnas,NumFilas,NumColumnas,matriz);
        ModeloAsignacion modelo_asignacion = new ModeloAsignacion();
        for(int i=0;i<NumFilas;i++){
            for(int j=0;j<NumColumnas;j++){
                System.out.print(matriz_original.matriz_original[i][j] + " ");
            }
            System.out.println("");
        }
        modelo_asignacion.obtenerMatrizFicticia(matriz_original);
        float matriz_final[][] = new float[NumFilas][NumColumnas];
        
        System.out.println("");
        for(int i=0;i<NumFilas;i++){
            for(int j=0;j<NumColumnas;j++){
                matriz_final[i][j] = matriz_original.matriz_original[i][j];
            }            
        }
        
        Resultados resultado_final = new Resultados();
        resultado_final.imprimir(matriz_final, NumFilas, NumColumnas);
    }
    
    /*
    public void inicializarTotalDatos(int NumFilas, int NumColumnas){
        totalDatos=NumFilas*NumColumnas;
        jTFNumDatosFaltantes.setText(Integer.toString(totalDatos));
    }*/
    
    
    public void llenarMatriz(){
        
        /*
        for(int i=0;i<NumFilas;i++){
            for(int j=0;j<NumColumnas;j++){
                
                TextoDatoMatriz=jTFDatoMatriz.getText();
                DatoMatriz= Integer.parseInt(TextoDatoMatriz);
                
                matriz[i][j]=DatoMatriz;
                
                jTFDatoMatriz.setText("");
                
                imprimirMatriz(matriz);
                
            }
        }
        
        for(int i=0;i<NumFilas;i++){
            for(int j=0;j<NumColumnas;j++){ 
                System.out.println(matriz[i][j]);
            }
        }*/
        
        TextoDatoMatriz = jTFDatoMatriz.getText();
        DatoMatriz = Float.parseFloat(TextoDatoMatriz);
        
        matriz[filaActual][columnaActual] = DatoMatriz;
        System.out.println(matriz[filaActual][columnaActual]);

        // Limpia el JTextField después de cada entrada
        jTFDatoMatriz.setText("");
/*
        jTFNumDatosFaltantes.setText(""+NumFilas*NumColumnas+(-1));
        jTFNumDatosFaltantes.setEnabled(false);
        */
        
        // Imprime la matriz hasta el momento (opcional)
        //imprimirMatriz(matriz);

        // Mueve el cursor a la siguiente posición en la matriz
        columnaActual++;
        totalDatos--;
        jTFNumDatosFaltantes.setText(Integer.toString(totalDatos));

     
        // Verifica si se completó una fila
        if (columnaActual == NumColumnas) {
            filaActual++;
            columnaActual = 0;
        }

        // Verifica si se llenó toda la matriz
        if (filaActual == NumFilas) {
            // Aquí puedes realizar cualquier acción adicional al completar la matriz
            System.out.println("Matriz completada");
            /*for (int i = 0; i < NumFilas; i++) {
                for (int j = 0; j < NumColumnas; j++) {
                    System.out.println(matriz[i][j]);
                }
        }*/
            imprimirMatriz(matriz);
        }
    }
    
    
    private void imprimirMatriz(float[][] matriz){
        for (int i = 0; i < NumFilas; i++) {
            for (int j = 0; j < NumColumnas; j++) {
                System.out.print(matriz[i][j] + " ");
            }
            System.out.println();
        }
        
        pasarmatriz(matriz);
        System.out.println();
}
    
    
    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        // TODO add your handling code here:
        /*
        String TextoNumFilas=jTFNumFilas.getText();
        int NumFilas=Integer.parseInt(TextoNumFilas);
        
        String TextoNumColumnas=jTFNumColumnas.getText();
        int NumColumnas=Integer.parseInt(TextoNumColumnas);*/
        
        /*String NombreFilas=jTFNombreFilas.getText();
        String NombreColumnas=jTFNombreColumnas.getText();*/
        
       /* String TextoDatoMatriz=jTFDatoMatriz.getText();
        int DatoMatriz=Integer.parseInt(TextoDatoMatriz);*/
        
        TextoNumFilas = jTFNumFilas.getText();
        NumFilas = Integer.parseInt(TextoNumFilas);

        TextoNumColumnas = jTFNumColumnas.getText();
        NumColumnas = Integer.parseInt(TextoNumColumnas);
       
        switch(clic){
            case 1:
                clic1();
                break;
            case 2:
                clic2();
                break;
            case 3:
                clic3();
                break;
            case 4:
                llenarMatriz();
                break;
            default:
                System.out.println("Noc");
        }
        
    }//GEN-LAST:event_jBAceptarActionPerformed

    public void cambiarPanel(){
        Resultados rm=new Resultados();
                
                //rm.setLayout(new BorderLayout());
                rm.setSize(848, 495);
                rm.setLocation(0, 0);

                
                jPanel1.removeAll();
                jPanel1.add(rm, BorderLayout.CENTER);
                jPanel1.revalidate();
                jPanel1.repaint();
    }
    
    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        // TODO add your handling code here:
        cambiarPanel();
        
        Resultados rs=new Resultados();
        rs.imprimir(matriz, NumFilas, NumColumnas);
        
        
    }//GEN-LAST:event_jBCalcularActionPerformed

    private void jTFNumFilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumFilasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumFilasActionPerformed

    private void jTFNumDatosFaltantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumDatosFaltantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumDatosFaltantesActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBCalcular;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JLabel jLPuntos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFDatoMatriz;
    private javax.swing.JTextField jTFNombreColumnas;
    private javax.swing.JTextField jTFNombreFilas;
    private javax.swing.JTextField jTFNumColumnas;
    private javax.swing.JTextField jTFNumDatosFaltantes;
    private javax.swing.JTextField jTFNumFilas;
    // End of variables declaration//GEN-END:variables
}
